In [117]:
import pandas as pd


path = "/Users/amalm/Downloads/dirty_customer_data_v2.csv"

df = pd.read_csv(path)

In [118]:
print(df.shape)
print(df.columns.tolist())

(668, 11)
['Customer_ID', 'Customer_Name', 'Country', 'City', 'Age', 'Signup_Date', 'Customer_Segment', 'Annual_Spend_DKK', 'Orders', 'Email', 'Active']

In [119]:
print(df.head(20))
#get an insight into how messy the data is and which columns need cleaning.

    Customer_ID     Customer_Name  Country          City   Age Signup_Date  \
0         10029     Elias Hussein  Denmark        Aarhus  51.0  2026-06-12
1         10219        Elias Holm  Germany           NaN   NaN  2025-04-17
2         10060    Sofia Petersen  Denmark        Odense  26.0  2026-04-29
3         10032       Sofia Rossi  Germany        Berlin  54.0  10/11/2025
4         10251   Mathias Poulsen   Sweden     Stockholm  28.0  2024-02-25
5         10472     Daniel Martin  Denmark       Aalborg  43.0  2025-06-08
6         10103   Mathias Poulsen       DK   Copenhagen   29.0  2024-04-05
7         10439      Emma Jensen    Sweden    Gothenburg  33.0  2026-05-20
8         10487  Lucas Kristensen  Denmark        Odense  27.0  2024-12-07
9         10643     Nora Eriksson  Denmark        Odense  66.0  2025-01-27
10        10195      Emily Wilson  Denmark    Copenhagen  21.0  06/04/2026
11        10194    Emil Johansson   Norway        Bergen  46.0  2024-07-17
12        10420      Amina Hassan  Germany       Hamburg  58.0  2024-07-14
13        10422      Lucas Garcia  Denmark           NaN  25.0  2024-03-26
14        10167         Noah Khan   Norway        Bergen  37.0  2025-07-08
15        10205      Yasmin Ahmed  Denmark        Odense  27.0  2026-01-06
16        10448     Daniel Martin   Sweden         Malmö  59.0  2025-01-06
17        10443     Maya Lindberg   Sweden     Stockholm   NaN  2024-06-24
18        10572      Ida Sørensen   Norway          Oslo  68.0  2024-01-10
19        10623        Leo Wagner  Germany        Berlin  59.0  2026-02-17

   Customer_Segment Annual_Spend_DKK  Orders                  Email Active
0             Basic         11882.96      10  user10029@example.com    Yes
1          Standard          6609.73      27  user10219@example.com    Yes
2          Standard         12872.17      33  user10060@example.com    Yes
3          Standard              NaN      17  user10032@example.com    Yes
4           Premium          9641.62      12  user10251@example.com     No
5           Premium          2541.67      16  user10472@example.com    Yes
6          Standard    17,827.26 DKK      20  user10103@example.com    Yes
7             Basic          2421.67      28  user10439@example.com    Yes
8          Standard          9325.31      25  USER10487@EXAMPLE.COM     No
9          Standard          9933.59      18  user10643@example.com    Yes
10         Standard          8684.79      31  user10195@example.com     No
11            Basic         11823.53      25  user10194@example.com    Yes
12         Standard         13996.86      15  user10420@example.com    Yes
13         Standard              NaN      18  user10422@example.com      N
14         Standard          3089.42       3  USER10167@EXAMPLE.COM    Yes
15         Standard         17898.44       9                    NaN    Yes
16          Premium         23978.06       2  user10448@example.com    Yes
17         Standard         11016.63      18  user10443@example.com    Yes
18         Standard          24899.3      16  user10572@example.com    YES
19            Basic              NaN      25  user10623@example.com    Yes

In [120]:
#I can see country is written as DK and denmark so that needs to be corrected

print(df['Country'].unique())

<StringArray>
[  'Denmark',   'Germany',    'Sweden',        'DK',    'Norway',   'DENMARK',
 ' Denmark ',   'Danmark',   'denmark']
Length: 9, dtype: str

In [121]:
#there are 7 ways Denmark is written in the country column

df['Country'] = df['Country'].replace([ 'denmark', ' Denmark ', 'Danmark', 'DK', 'DANMARK', 'DENMARK' ], 'Denmark')

In [122]:
print(df['Country'].unique())

<StringArray>
['Denmark', 'Germany', 'Sweden', 'Norway']
Length: 4, dtype: str

In [123]:
#Correct City

df['City'] = df['City'].str.capitalize()

In [124]:
df['City'].unique()

<StringArray>
[      'Aarhus',            nan,       'Odense',       'Berlin',
    'Stockholm',      'Aalborg', ' copenhagen ',   'Gothenburg',
   'Copenhagen',       'Bergen',      'Hamburg',        'Malmö',
         'Oslo',    'København',       'Ålborg',     ' odense ',
        'Århus']
Length: 17, dtype: str

In [125]:
df['City'] = df['City'].replace(['openhagen', 'Copenhagen', 'copenhagen', 'københavn', 'københavn', ' copenhagen ', 'COPENHAGEN', ' Copenhagen ','København'], 'Copenhagen')

In [126]:
df['City'] = df['City'].replace(['aarhus', 'århus', 'AARHUS', 'Århus'], 'Aarhus')

In [127]:
df['City'] = df['City'].replace(['odense', ' odense ', ' Odense ','ODENSE'], 'Odense')

In [128]:
df['City'] = df['City'].replace(['aalborg', 'ålborg', 'AALBORG', 'Ålborg'], 'Aalborg')

In [129]:
df['City'].unique()

<StringArray>
[    'Aarhus',          nan,     'Odense',     'Berlin',  'Stockholm',
    'Aalborg', 'Copenhagen', 'Gothenburg',     'Bergen',    'Hamburg',
      'Malmö',       'Oslo']
Length: 12, dtype: str

In [130]:
#Correct Signup_Date

df['Signup_Date'].dtype

In [131]:
df['Signup_Date'] = pd.to_datetime(
    df['Signup_Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [132]:
print(df['Annual_Spend_DKK'].dtype)

str

In [133]:
#remove DKK & , from Annual spend DKK
df['Annual_Spend_DKK'] = df['Annual_Spend_DKK'].str.replace('DKK', '')
df['Annual_Spend_DKK'] = df['Annual_Spend_DKK'].str.replace(',', '')

In [134]:
df['Annual_Spend_DKK'] = pd.to_numeric(
   df['Annual_Spend_DKK'],
   errors= 'coerce' 
)

In [135]:
print(df[df['Annual_Spend_DKK'] <0])

     Customer_ID  Customer_Name  Country     City   Age Signup_Date  \
664        10503  Maya Lindberg  Germany  Hamburg  18.0  2026-05-14

    Customer_Segment  Annual_Spend_DKK  Orders                  Email Active
664         Standard           -2500.0      25  user10503@example.com    Yes

In [136]:
#Find Annual_Spend_DKK
df.loc[df['Annual_Spend_DKK'] < 0, 'Annual_Spend_DKK'] = 0

In [137]:
print("Missing dates:", df['Signup_Date'].isna().sum())
print("Missing spend:", df['Annual_Spend_DKK'].isna().sum())

Missing dates: 7
Missing spend: 27

In [138]:
df['Age'].dtype

dtype('float64')

In [139]:
df['Age'] = df['Age'].astype('Int64')

In [140]:
#check age not > 100
print(df[df['Age'] > 100])

     Customer_ID Customer_Name Country   City  Age Signup_Date  \
517        10483   Emma Jensen  Sweden  Malmö  143  2024-12-27

    Customer_Segment  Annual_Spend_DKK  Orders                  Email Active
517         Standard           9075.07       6  user10483@example.com    Yes

In [141]:
#Find age < 0
print(df[df['Age'] < 0])

     Customer_ID    Customer_Name  Country     City  Age Signup_Date  \
138        10497    Omar Mohamed   Denmark  Aalborg   -8  2025-08-02

    Customer_Segment  Annual_Spend_DKK  Orders                  Email Active
138          Premium          12470.62       7  user10497@example.com    Yes

In [142]:
# Convert age  < 0 to NaN
df.loc[df['Age'] < 0, 'Age'] = pd.NA

In [143]:
# Convert age >100 to NaN
df.loc[df['Age'] >100, 'Age'] = pd.NA

In [144]:
#Check to see if it has been changed
print(df[df['Age'] > 100])
print(df[df['Age'] < 0])

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Country, City, Age, Signup_Date, Customer_Segment, Annual_Spend_DKK, Orders, Email, Active]
Index: []
Empty DataFrame
Columns: [Customer_ID, Customer_Name, Country, City, Age, Signup_Date, Customer_Segment, Annual_Spend_DKK, Orders, Email, Active]
Index: []

In [145]:
df['Orders'].dtype

dtype('int64')

In [146]:
#convert orders to integer to remove .0
df['Orders'] = df['Orders'].astype('Int64')

In [147]:
#Find orders <0 
print(df[df['Orders'] <0])

     Customer_ID Customer_Name  Country     City  Age Signup_Date  \
586        10290  Mads Nielsen  Denmark  Aalborg   28  2026-01-14

    Customer_Segment  Annual_Spend_DKK  Orders                  Email Active
586         Standard           4921.36      -3  user10290@example.com     No

In [148]:
df.loc[df['Orders'] <0, 'Orders'] = pd.NA

In [149]:
#Check to see orders < o have been changed
print(df[df['Orders'] <0])

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Country, City, Age, Signup_Date, Customer_Segment, Annual_Spend_DKK, Orders, Email, Active]
Index: []

In [150]:
print("Min:", df['Orders'].min())
print("Max:", df['Orders'].max())

Min: 0
Max: 999

In [151]:
#Email

df['Email'] = df['Email'].str.lower()

In [152]:

# Show emails that do not contain @
df[df['Email'].notna() & ~df['Email'].str.contains('@')]

,Customer_ID,Customer_Name,Country,City,Age,Signup_Date,Customer_Segment,Annual_Spend_DKK,Orders,Email,Active
92,10428,Adam Ali,Norway,Oslo,58,2025-11-23,Standard,6564.18,18,missing-at-sign.com,Yes
298,10425,Sara Mohamed,Sweden,Gothenburg,38,2025-04-08,Standard,10141.59,12,missing-at-sign.com,Yes
355,10478,Freja Møller,Sweden,Stockholm,62,2025-04-19,Standard,10754.09,10,missing-at-sign.com,Yes
447,10507,Emma Jensen,Denmark,Aalborg,64,2025-07-27,premium,21504.47,12,user.example.com,No
463,10447,Omar Mohamed,Germany,Berlin,57,2024-10-04,Standard,12446.87,3,user.example.com,Yes
470,10342,Clara Andersen,Germany,Hamburg,68,2024-09-22,Standard,3213.66,7,missing-at-sign.com,No

In [153]:
# Emails without @ --> NaN
df.loc[
    df['Email'].notna() & ~df['Email'].str.contains('@'),
    'Email'
] = pd.NA

In [154]:
#Check that there are no Email adresses left without @
df[df['Email'].notna() & ~df['Email'].str.contains('@')]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Country, City, Age, Signup_Date, Customer_Segment, Annual_Spend_DKK, Orders, Email, Active]
Index: []

In [155]:
#Find Emails withut UserID
df[df['Email'].notna() & ~df['Email'].str.contains('user')]

,Customer_ID,Customer_Name,Country,City,Age,Signup_Date,Customer_Segment,Annual_Spend_DKK,Orders,Email,Active
251,10489,Maya Lindberg,Denmark,Aalborg,30,2025-08-24,Standard,13255.52,34,@example.com,Yes
272,10192,Elias Holm,Denmark,Aalborg,26,2024-01-23,Standard,7184.50,3,@example.com,Yes
282,10385,Sofia Petersen,Denmark,Odense,56,2026-05-14,PREMIUM,14522.80,11,@example.com,Yes
323,10535,Emily Wilson,Denmark,Copenhagen,56,2026-05-06,standard,20237.21,9,@example.com,No

In [156]:
# Emails without UserID --> NaN
df.loc[
    df['Email'].notna() & ~df['Email'].str.contains('user'),
    'Email'
] = pd.NA

In [157]:
#check that there are no Email adresses left without userID 
df[df['Email'].notna() & ~df['Email'].str.contains('user')]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Country, City, Age, Signup_Date, Customer_Segment, Annual_Spend_DKK, Orders, Email, Active]
Index: []

In [158]:
#Customer_Segment

df['Customer_Segment'].unique()

<StringArray>
[    'Basic',  'Standard',   'Premium',  ' Premium',   'PREMIUM', 'Standard ',
     'basic',     'BASIC', 'standard ',   'premium']
Length: 10, dtype: str

In [159]:
df['Customer_Segment'] = df['Customer_Segment'].replace(['basic', 'BASIC'], 'Basic')

In [160]:
df['Customer_Segment'] = df['Customer_Segment'].replace(['Standard ', 'standard '], 'Standard')

In [161]:
df['Customer_Segment'] = df['Customer_Segment'].replace([' Premium', 'PREMIUM', 'premium' ], 'Premium')

In [162]:
#check the Customer_Segement

df['Customer_Segment'].unique()

<StringArray>
['Basic', 'Standard', 'Premium']
Length: 3, dtype: str

In [163]:
print(df.head())

   Customer_ID    Customer_Name  Country       City   Age Signup_Date  \
0        10029    Elias Hussein  Denmark     Aarhus    51  2026-12-06
1        10219       Elias Holm  Germany        NaN  <NA>  2025-04-17
2        10060   Sofia Petersen  Denmark     Odense    26  2026-04-29
3        10032      Sofia Rossi  Germany     Berlin    54  2025-11-10
4        10251  Mathias Poulsen   Sweden  Stockholm    28  2024-02-25

  Customer_Segment  Annual_Spend_DKK  Orders                  Email Active
0            Basic          11882.96      10  user10029@example.com    Yes
1         Standard           6609.73      27  user10219@example.com    Yes
2         Standard          12872.17      33  user10060@example.com    Yes
3         Standard               NaN      17  user10032@example.com    Yes
4          Premium           9641.62      12  user10251@example.com     No

In [164]:
print("duplicates:\n", df[df.duplicated(keep=False)])

duplicates:
      Customer_ID     Customer_Name  Country        City   Age Signup_Date  \
9          10643     Nora Eriksson  Denmark      Odense    66  2025-01-27
17         10443     Maya Lindberg   Sweden   Stockholm  <NA>  2024-06-24
104        10003     Elias Hussein   Norway        Oslo    60  2024-05-20
131        10096      Yasmin Ahmed   Sweden  Gothenburg    37  2025-11-14
146        10481      Mads Nielsen  Denmark      Aarhus    41  2025-11-10
151        10204      Anna Schmidt  Denmark      Odense    21  2024-09-11
164        10278      Daniel Brown  Denmark     Aalborg    68  2024-03-22
182        10254        Lina Osman  Denmark  Copenhagen    22  2024-06-30
232        10254        Lina Osman  Denmark  Copenhagen    22  2024-06-30
242        10450       Sofia Rossi   Sweden  Gothenburg  <NA>  2025-11-14
249        10204      Anna Schmidt  Denmark      Odense    21  2024-09-11
271        10481      Mads Nielsen  Denmark      Aarhus    41  2025-11-10
276        10172     Elias Hussein  Denmark     Aalborg    20  2025-10-12
330        10136      Sofie Larsen  Denmark      Odense    25  2024-10-08
377        10136      Sofie Larsen  Denmark      Odense    25  2024-10-08
379        10550      Freja Møller  Denmark     Aalborg    23  2024-02-19
381        10326      Omar Mohamed   Sweden   Stockholm    27  2025-09-09
384        10643     Nora Eriksson  Denmark      Odense    66  2025-01-27
394        10172     Elias Hussein  Denmark     Aalborg    20  2025-10-12
402        10202     Laura Thomsen  Germany     Hamburg    42  2024-02-19
409        10550      Freja Møller  Denmark     Aalborg    23  2024-02-19
424        10308      Yasmin Ahmed   Sweden   Stockholm    69  2024-07-11
439        10308      Yasmin Ahmed   Sweden   Stockholm    69  2024-07-11
449        10003     Elias Hussein   Norway        Oslo    60  2024-05-20
467        10096      Yasmin Ahmed   Sweden  Gothenburg    37  2025-11-14
486        10145  William Pedersen  Denmark      Aarhus    28  2024-10-30
490        10202     Laura Thomsen  Germany     Hamburg    42  2024-02-19
503        10326      Omar Mohamed   Sweden   Stockholm    27  2025-09-09
528        10145  William Pedersen  Denmark      Aarhus    28  2024-10-30
534        10166      Sofie Larsen  Denmark      Aarhus    46  2025-01-06
546        10299        Leo Wagner   Norway        Oslo    61  2024-03-10
567        10166      Sofie Larsen  Denmark      Aarhus    46  2025-01-06
571        10299        Leo Wagner   Norway        Oslo    61  2024-03-10
574        10278      Daniel Brown  Denmark     Aalborg    68  2024-03-22
649        10443     Maya Lindberg   Sweden   Stockholm  <NA>  2024-06-24
659        10450       Sofia Rossi   Sweden  Gothenburg  <NA>  2025-11-14

    Customer_Segment  Annual_Spend_DKK  Orders                    Email Active
9           Standard           9933.59      18    user10643@example.com    Yes
17          Standard          11016.63      18    user10443@example.com    Yes
104            Basic           7870.16       3    user10003@example.com    Yes
131          Premium           4748.74      33    user10096@example.com    Yes
146         Standard          20091.25      11    user10481@example.com    Yes
151            Basic          12702.43      28    user10204@example.com     no
164          Premium           5308.66      24    user10278@example.com    Yes
182          Premium          13332.82      25    user10254@example.com    Yes
232          Premium          13332.82      25    user10254@example.com    Yes
242         Standard           8545.24      24    user10450@example.com    Yes
249            Basic          12702.43      28    user10204@example.com     no
271         Standard          20091.25      11    user10481@example.com    Yes
276          Premium          17678.34       6   user10172@example.com     Yes
330         Standard           8434.08      34    user10136@example.com    Yes
377         Standard           8434.08      34    user10136@example.com    Yes
379          Premium          18064.61      31    user10550@example.com    Yes
381          Premium           6460.65      32    user10326@example.com    Yes
384         Standard           9933.59      18    user10643@example.com    Yes
394          Premium          17678.34       6   user10172@example.com     Yes
402          Premium           8772.54      31                      NaN    Yes
409          Premium          18064.61      31    user10550@example.com    Yes
424            Basic           6640.89      23    user10308@example.com    YES
439            Basic           6640.89      23    user10308@example.com    YES
449            Basic           7870.16       3    user10003@example.com    Yes
467          Premium           4748.74      33    user10096@example.com    Yes
486            Basic          30283.17       9    user10145@example.com    Yes
490          Premium           8772.54      31                      NaN    Yes
503          Premium           6460.65      32    user10326@example.com    Yes
528            Basic          30283.17       9    user10145@example.com    Yes
534            Basic           7045.70       7    user10166@example.com    Yes
546         Standard          17105.95      21    user10299@example.com     No
567            Basic           7045.70       7    user10166@example.com    Yes
571         Standard          17105.95      21    user10299@example.com     No
574          Premium           5308.66      24    user10278@example.com    Yes
649         Standard          11016.63      18    user10443@example.com    Yes
659         Standard           8545.24      24    user10450@example.com    Yes

In [165]:

print("Number of duplicate rows:", df.duplicated(keep=False).sum())

Number of duplicate rows: 36

In [166]:
print("Rows involved in duplicates:", df.duplicated(keep=False).sum())
print("Duplicate rows to remove:", df.duplicated().sum())

Rows involved in duplicates: 36
Duplicate rows to remove: 18

In [167]:
#Check the duplicates Customer_ID --> 100% identical
df[df.duplicated(subset='Customer_ID', keep=False)]

,Customer_ID,Customer_Name,Country,City,Age,Signup_Date,Customer_Segment,Annual_Spend_DKK,Orders,Email,Active
9,10643,Nora Eriksson,Denmark,Odense,66,2025-01-27,Standard,9933.59,18,user10643@example.com,Yes
17,10443,Maya Lindberg,Sweden,Stockholm,<NA>,2024-06-24,Standard,11016.63,18,user10443@example.com,Yes
104,10003,Elias Hussein,Norway,Oslo,60,2024-05-20,Basic,7870.16,3,user10003@example.com,Yes
131,10096,Yasmin Ahmed,Sweden,Gothenburg,37,2025-11-14,Premium,4748.74,33,user10096@example.com,Yes
146,10481,Mads Nielsen,Denmark,Aarhus,41,2025-11-10,Standard,20091.25,11,user10481@example.com,Yes
151,10204,Anna Schmidt,Denmark,Odense,21,2024-09-11,Basic,12702.43,28,user10204@example.com,no
164,10278,Daniel Brown,Denmark,Aalborg,68,2024-03-22,Premium,5308.66,24,user10278@example.com,Yes
182,10254,Lina Osman,Denmark,Copenhagen,22,2024-06-30,Premium,13332.82,25,user10254@example.com,Yes
232,10254,Lina Osman,Denmark,Copenhagen,22,2024-06-30,Premium,13332.82,25,user10254@example.com,Yes
242,10450,Sofia Rossi,Sweden,Gothenburg,<NA>,2025-11-14,Standard,8545.24,24,user10450@example.com,Yes
249,10204,Anna Schmidt,Denmark,Odense,21,2024-09-11,Basic,12702.43,28,user10204@example.com,no
271,10481,Mads Nielsen,Denmark,Aarhus,41,2025-11-10,Standard,20091.25,11,user10481@example.com,Yes
276,10172,Elias Hussein,Denmark,Aalborg,20,2025-10-12,Premium,17678.34,6,user10172@example.com,Yes
330,10136,Sofie Larsen,Denmark,Odense,25,2024-10-08,Standard,8434.08,34,user10136@example.com,Yes
377,10136,Sofie Larsen,Denmark,Odense,25,2024-10-08,Standard,8434.08,34,user10136@example.com,Yes
379,10550,Freja Møller,Denmark,Aalborg,23,2024-02-19,Premium,18064.61,31,user10550@example.com,Yes
381,10326,Omar Mohamed,Sweden,Stockholm,27,2025-09-09,Premium,6460.65,32,user10326@example.com,Yes
384,10643,Nora Eriksson,Denmark,Odense,66,2025-01-27,Standard,9933.59,18,user10643@example.com,Yes
394,10172,Elias Hussein,Denmark,Aalborg,20,2025-10-12,Premium,17678.34,6,user10172@example.com,Yes
402,10202,Laura Thomsen,Germany,Hamburg,42,2024-02-19,Premium,8772.54,31,NaN,Yes
409,10550,Freja Møller,Denmark,Aalborg,23,2024-02-19,Premium,18064.61,31,user10550@example.com,Yes
424,10308,Yasmin Ahmed,Sweden,Stockholm,69,2024-07-11,Basic,6640.89,23,user10308@example.com,YES
439,10308,Yasmin Ahmed,Sweden,Stockholm,69,2024-07-11,Basic,6640.89,23,user10308@example.com,YES
449,10003,Elias Hussein,Norway,Oslo,60,2024-05-20,Basic,7870.16,3,user10003@example.com,Yes
467,10096,Yasmin Ahmed,Sweden,Gothenburg,37,2025-11-14,Premium,4748.74,33,user10096@example.com,Yes
486,10145,William Pedersen,Denmark,Aarhus,28,2024-10-30,Basic,30283.17,9,user10145@example.com,Yes
490,10202,Laura Thomsen,Germany,Hamburg,42,2024-02-19,Premium,8772.54,31,NaN,Yes
503,10326,Omar Mohamed,Sweden,Stockholm,27,2025-09-09,Premium,6460.65,32,user10326@example.com,Yes
528,10145,William Pedersen,Denmark,Aarhus,28,2024-10-30,Basic,30283.17,9,user10145@example.com,Yes
534,10166,Sofie Larsen,Denmark,Aarhus,46,2025-01-06,Basic,7045.70,7,user10166@example.com,Yes
546,10299,Leo Wagner,Norway,Oslo,61,2024-03-10,Standard,17105.95,21,user10299@example.com,No
567,10166,Sofie Larsen,Denmark,Aarhus,46,2025-01-06,Basic,7045.70,7,user10166@example.com,Yes
571,10299,Leo Wagner,Norway,Oslo,61,2024-03-10,Standard,17105.95,21,user10299@example.com,No
574,10278,Daniel Brown,Denmark,Aalborg,68,2024-03-22,Premium,5308.66,24,user10278@example.com,Yes
649,10443,Maya Lindberg,Sweden,Stockholm,<NA>,2024-06-24,Standard,11016.63,18,user10443@example.com,Yes
659,10450,Sofia Rossi,Sweden,Gothenburg,<NA>,2025-11-14,Standard,8545.24,24,user10450@example.com,Yes

In [168]:
df = df.drop_duplicates()

In [169]:
print("Duplicates:", df.duplicated(keep=False).sum())

Duplicates: 0

In [170]:
print(df.head(30))

    Customer_ID     Customer_Name  Country        City   Age Signup_Date  \
0         10029     Elias Hussein  Denmark      Aarhus    51  2026-12-06
1         10219        Elias Holm  Germany         NaN  <NA>  2025-04-17
2         10060    Sofia Petersen  Denmark      Odense    26  2026-04-29
3         10032       Sofia Rossi  Germany      Berlin    54  2025-11-10
4         10251   Mathias Poulsen   Sweden   Stockholm    28  2024-02-25
5         10472     Daniel Martin  Denmark     Aalborg    43  2025-08-06
6         10103   Mathias Poulsen  Denmark  Copenhagen    29  2024-05-04
7         10439      Emma Jensen    Sweden  Gothenburg    33  2026-05-20
8         10487  Lucas Kristensen  Denmark      Odense    27  2024-07-12
9         10643     Nora Eriksson  Denmark      Odense    66  2025-01-27
10        10195      Emily Wilson  Denmark  Copenhagen    21  2026-04-06
11        10194    Emil Johansson   Norway      Bergen    46  2024-07-17
12        10420      Amina Hassan  Germany     Hamburg    58  2024-07-14
13        10422      Lucas Garcia  Denmark         NaN    25  2024-03-26
14        10167         Noah Khan   Norway      Bergen    37  2025-08-07
15        10205      Yasmin Ahmed  Denmark      Odense    27  2026-06-01
16        10448     Daniel Martin   Sweden       Malmö    59  2025-06-01
17        10443     Maya Lindberg   Sweden   Stockholm  <NA>  2024-06-24
18        10572      Ida Sørensen   Norway        Oslo    68  2024-10-01
19        10623        Leo Wagner  Germany      Berlin    59  2026-02-17
20        10522      Elena Müller  Denmark      Aarhus    71  2024-10-24
21        10465      Yasmin Ahmed  Denmark  Copenhagen    56  2025-10-14
22        10373     Laura Thomsen  Denmark  Copenhagen    50         NaT
23        10636      Freja Møller  Denmark      Odense    48  2025-01-07
24        10078      Elena Müller   Sweden  Gothenburg    65  2024-08-07
25        10390     Oliver Hansen   Norway        Oslo    41  2025-11-07
26        10549      Amina Hassan   Norway        Oslo    71  2024-10-01
27        10017       Sofia Rossi  Denmark  Copenhagen    71  2025-10-26
28        10375       Sofia Rossi  Denmark      Odense    18  2026-01-19
29        10452  Victor Lindström  Germany      Berlin    27  2024-07-26

   Customer_Segment  Annual_Spend_DKK  Orders                  Email Active
0             Basic          11882.96      10  user10029@example.com    Yes
1          Standard           6609.73      27  user10219@example.com    Yes
2          Standard          12872.17      33  user10060@example.com    Yes
3          Standard               NaN      17  user10032@example.com    Yes
4           Premium           9641.62      12  user10251@example.com     No
5           Premium           2541.67      16  user10472@example.com    Yes
6          Standard          17827.26      20  user10103@example.com    Yes
7             Basic           2421.67      28  user10439@example.com    Yes
8          Standard           9325.31      25  user10487@example.com     No
9          Standard           9933.59      18  user10643@example.com    Yes
10         Standard           8684.79      31  user10195@example.com     No
11            Basic          11823.53      25  user10194@example.com    Yes
12         Standard          13996.86      15  user10420@example.com    Yes
13         Standard               NaN      18  user10422@example.com      N
14         Standard           3089.42       3  user10167@example.com    Yes
15         Standard          17898.44       9                    NaN    Yes
16          Premium          23978.06       2  user10448@example.com    Yes
17         Standard          11016.63      18  user10443@example.com    Yes
18         Standard          24899.30      16  user10572@example.com    YES
19            Basic               NaN      25  user10623@example.com    Yes
20            Basic           3082.47      17  user10522@example.com    Yes
21         Standard           4706.87       2  user10465@example.com    Yes
22         Standard          18969.47      17  user10373@example.com    yes
23         Standard          11967.22      27  user10636@example.com    Yes
24         Standard          16280.63       5  user10078@example.com    Yes
25          Premium           7077.11      30  user10390@example.com    Yes
26            Basic          14033.73       4  user10549@example.com    Yes
27         Standard          11278.94      27  user10017@example.com    Yes
28         Standard               NaN      11  user10375@example.com    Yes
29            Basic         999999.00      15  user10452@example.com    Yes

In [171]:
df.isna().sum()

Customer_ID          0
Customer_Name        0
Country              0
City                18
Age                 26
Signup_Date          7
Customer_Segment     0
Annual_Spend_DKK    27
Orders               1
Email               31
Active               0
dtype: int64

In [172]:
# save cleaned data

df.to_csv('cleaneddataset.csv')